#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Allow Ctrl-R to be used in conjunction with vi keybindings
#
bindkey -M viins '^r' history-incremental-search-backward
bindkey -M vicmd '^r' history-incremental-search-backward

# alias the ssh command to allow the TERM env var to be fixed
#
alias ssh='TERM=xterm ssh'

# alias the tmux command to force 256 colours on start
#
alias tmux='tmux -2'
